/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author user
 */
public class Station extends javax.swing.JFrame {

    /**
     * Creates new form Station
     */
    public Station() {
        initComponents();
    }

    Station(Object object, boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Station = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        origin = new javax.swing.JComboBox<>();
        destination = new javax.swing.JComboBox<>();
        time = new javax.swing.JLabel();
        people = new javax.swing.JLabel();
        money = new javax.swing.JLabel();
        generate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(430, 400));
        setResizable(false);
        getContentPane().setLayout(null);

        Station.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Station.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Station.setText("Station");
        getContentPane().add(Station);
        Station.setBounds(107, 32, 175, 42);

        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back);
        back.setBounds(10, 299, 84, 32);

        origin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Taling Chan", "Bang Bamru", "Bang Son", "Bang Sue Grand Station", "Chatuchak", "Wat Samian Nari", "Bang Khen", "Thung Song Hong", "Lak Si", "Kan Khaha", "Don Mueang", "Lak Hok", "Rangsit" }));
        origin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                originActionPerformed(evt);
            }
        });
        getContentPane().add(origin);
        origin.setBounds(61, 92, 134, 44);

        destination.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Taling Chan", "Bang Bamru", "Bang Son", "Bang Sue Grand Station", "Chatuchak", "Wat Samian Nari", "Bang Khen", "Thung Song Hong", "Lak Si", "Kan Khaha", "Don Mueang", "Lak Hok", "Rangsit" }));
        getContentPane().add(destination);
        destination.setBounds(213, 92, 134, 44);

        time.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        time.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(time);
        time.setBounds(130, 260, 150, 30);

        people.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        people.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(people);
        people.setBounds(130, 190, 150, 30);

        money.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        money.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(money);
        money.setBounds(130, 230, 150, 30);

        generate.setText("generate");
        generate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateActionPerformed(evt);
            }
        });
        getContentPane().add(generate);
        generate.setBounds(160, 150, 90, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        this.dispose();
        PayMoney PayM = new PayMoney();
        PayM.setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void originActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_originActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_originActionPerformed

    private void generateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateActionPerformed
       // TODO add your handling code here:
    }//GEN-LAST:event_generateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Station.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Station.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Station.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Station.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Station().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Station;
    private javax.swing.JButton back;
    private javax.swing.JComboBox<String> destination;
    private javax.swing.JButton generate;
    private javax.swing.JLabel money;
    private javax.swing.JComboBox<String> origin;
    private javax.swing.JLabel people;
    private javax.swing.JLabel time;
    // End of variables declaration//GEN-END:variables
}
